# Generated by Django 5.1.2 on 2024-10-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='plot',
            field=models.TextField(default=''),
        ),
    ]
